### Health Check Endpoint
GET http://localhost:8080/health
Accept: application/json

### Read Item Endpoint
GET http://localhost:8080/items/1
Accept: application/json

### Gateway Endpoints

#### GET Request to Service A
GET http://localhost:8080/service-a/some-path
Accept: application/json
Authorization: Bearer <your_token>

#### POST Request to Service A
POST http://localhost:8080/service-a/some-path
Accept: application/json
Content-Type: application/json
Authorization: Bearer <your_token>

{
  "key": "value"
}

#### PUT Request to Service A
PUT http://localhost:8080/service-a/some-path
Accept: application/json
Content-Type: application/json
Authorization: Bearer <your_token>

{
  "key": "value"
}

#### DELETE Request to Service A
DELETE http://localhost:8080/service-a/some-path
Accept: application/json
Authorization: Bearer <your_token>

#### PATCH Request to Service A
PATCH http://localhost:8080/service-a/some-path
Accept: application/json
Content-Type: application/json
Authorization: Bearer <your_token>

{
  "key": "value"
}